package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"log"

	"github.com/playingwithclouds/veil/internal/api/graphql/generated"
	"github.com/playingwithclouds/veil/internal/api/graphql/model"
	"github.com/playingwithclouds/veil/internal/subscriptions"
	"github.com/playingwithclouds/veil/internal/vpn"
)

// Scrape is the resolver for the scrape field.
func (r *mutationResolver) Scrape(ctx context.Context, pluginName string, url string) (*model.ScrapePayload, error) {
	if _, err := r.orchestrator.EnqueueScrape(ctx, pluginName, url); err != nil {
		message := err.Error()
		return &model.ScrapePayload{Success: false, Error: &message}, nil
	}
	return &model.ScrapePayload{Success: true}, nil
}

// QueueDownload is the resolver for the queueDownload field.
func (r *mutationResolver) QueueDownload(ctx context.Context, url string, title string, pluginName *string) (string, error) {
	plugin := ""
	if pluginName != nil {
		plugin = *pluginName
	}
	return r.orchestrator.EnqueueDownload(ctx, url, title, plugin)
}

// VpnStatus is the resolver for the vpnStatus field.
func (r *queryResolver) VpnStatus(ctx context.Context) (*model.VpnStatus, error) {
	connected, iface := vpn.IsConnected()
	status := &model.VpnStatus{Connected: connected}
	if iface != "" {
		status.Interface = &iface
	}
	return status, nil
}

// Stream is the resolver for the stream field.
func (r *queryResolver) Stream(ctx context.Context, url string, pluginName *string) (*model.StreamResult, error) {
	result, err := r.streamSvc.Resolve(ctx, url)
	if err != nil {
		return nil, err
	}

	playableURL := result.URL
	if r.streamProxy != nil {
		if manifestURL, err := r.streamProxy.ManifestURL(ctx, result); err == nil {
			playableURL = manifestURL
		}
	}

	headers := make([]*model.StreamHeader, 0, len(result.Headers))
	for name, value := range result.Headers {
		headers = append(headers, &model.StreamHeader{Name: name, Value: value})
	}

	stream := &model.StreamResult{
		URL:      playableURL,
		MimeType: result.MimeType,
		Headers:  headers,
	}
	if result.Quality != "" {
		stream.Quality = &result.Quality
	}
	if result.LoadTimeMs > 0 {
		loadTime := float64(result.LoadTimeMs)
		stream.LoadTimeMs = &loadTime
	}
	if result.SpeedBps > 0 {
		stream.SpeedBps = &result.SpeedBps
	}
	return stream, nil
}

// CheckProviderSpeeds is the resolver for the checkProviderSpeeds field.
func (r *queryResolver) CheckProviderSpeeds(ctx context.Context, id string) ([]*model.ProviderSpeed, error) {
	streams, err := r.repo.ListStreams(ctx, id)
	if err != nil {
		return nil, err
	}

	speeds := make([]*model.ProviderSpeed, 0, len(streams))
	for _, s := range streams {
		speed := &model.ProviderSpeed{URL: s.URL}
		result, err := r.streamSvc.Resolve(ctx, s.URL)
		if err != nil {
			message := err.Error()
			speed.Error = &message
		} else {
			loadTime := float64(result.LoadTimeMs)
			speed.LoadTimeMs = &loadTime
			speed.SpeedBps = &result.SpeedBps
		}
		speeds = append(speeds, speed)
	}
	return speeds, nil
}

// MediaAdded is the resolver for the mediaAdded field.
func (r *subscriptionResolver) MediaAdded(ctx context.Context) (<-chan *model.MediaEvent, error) {
	panic(fmt.Errorf("not implemented: MediaAdded - mediaAdded"))
}

// JobUpdated is the resolver for the jobUpdated field.
func (r *subscriptionResolver) JobUpdated(ctx context.Context) (<-chan *model.Job, error) {
	panic(fmt.Errorf("not implemented: JobUpdated - jobUpdated"))
}

// StreamsChanged streams the media item's ranked sources: an initial snapshot,
// then a fresh list on every change (new streams ingested, speed-check re-rank).
func (r *subscriptionResolver) StreamsChanged(ctx context.Context, mediaID string) (<-chan []*model.Stream, error) {
	if r.hub == nil {
		return nil, fmt.Errorf("subscriptions unavailable")
	}

	out := make(chan []*model.Stream, 1)
	events, cancel := r.hub.Subscribe(subscriptions.StreamsTopic(mediaID))

	emit := func() {
		streams, err := r.loadRankedStreams(ctx, mediaID)
		if err != nil {
			log.Printf("streamsChanged: load %s: %v", mediaID, err)
			return
		}
		select {
		case out <- streams:
		case <-ctx.Done():
		}
	}

	go func() {
		defer cancel()
		defer close(out)
		emit() // initial snapshot so the client syncs on connect
		for {
			select {
			case <-ctx.Done():
				return
			case _, ok := <-events:
				if !ok {
					return
				}
				emit()
			}
		}
	}()

	return out, nil
}

// RelatedChanged is the resolver for the relatedChanged field.
func (r *subscriptionResolver) RelatedChanged(ctx context.Context, sceneID string) (<-chan []*model.Scene, error) {
	if r.hub == nil {
		return nil, fmt.Errorf("subscriptions unavailable")
	}
	out := make(chan []*model.Scene, 1)
	events, cancel := r.hub.Subscribe(subscriptions.RelatedTopic(sceneID))

	emit := func() {
		scenes, err := r.repo.RelatedScenes(ctx, sceneID, relatedSubscriptionLimit, r.registry.InactiveNames())
		if err != nil {
			log.Printf("relatedChanged: load %s: %v", sceneID, err)
			return
		}
		select {
		case out <- scenes:
		case <-ctx.Done():
		}
	}

	go func() {
		defer cancel()
		defer close(out)
		emit() // initial snapshot so the client syncs on connect
		for {
			select {
			case <-ctx.Done():
				return
			case _, ok := <-events:
				if !ok {
					return
				}
				emit()
			}
		}
	}()
	return out, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
