package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
)

// AddBlock is the resolver for the addBlock field.
func (r *mutationResolver) AddBlock(ctx context.Context, kind string, targetID string, label *string) (*model.BlocklistEntry, error) {
	return r.repo.AddBlock(ctx, kind, targetID, label)
}

// RemoveBlock is the resolver for the removeBlock field.
func (r *mutationResolver) RemoveBlock(ctx context.Context, targetID string) (bool, error) {
	return r.repo.RemoveBlock(ctx, targetID)
}

// Blocklist is the resolver for the blocklist field.
func (r *queryResolver) Blocklist(ctx context.Context) ([]*model.BlocklistEntry, error) {
	return r.repo.ListBlocklist(ctx)
}
