package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
)

// Changes is the resolver for the changes field.
func (r *queryResolver) Changes(ctx context.Context, targetID string, key *string, limit *int, offset *int) ([]*model.Change, error) {
	panic(fmt.Errorf("not implemented: Changes - changes"))
}
