package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
)

// CreateCollection is the resolver for the createCollection field.
func (r *mutationResolver) CreateCollection(ctx context.Context, name string) (*model.Collection, error) {
	return r.repo.CreateCollection(ctx, name)
}

// RenameCollection is the resolver for the renameCollection field.
func (r *mutationResolver) RenameCollection(ctx context.Context, collectionID string, name string) (*model.Collection, error) {
	return r.repo.RenameCollection(ctx, collectionID, name)
}

// DeleteCollection is the resolver for the deleteCollection field.
func (r *mutationResolver) DeleteCollection(ctx context.Context, collectionID string) (bool, error) {
	return r.repo.DeleteCollection(ctx, collectionID)
}

// AddToCollection is the resolver for the addToCollection field.
func (r *mutationResolver) AddToCollection(ctx context.Context, collectionID string, mediaID string) (bool, error) {
	return r.repo.AddToCollection(ctx, collectionID, mediaID)
}

// RemoveFromCollection is the resolver for the removeFromCollection field.
func (r *mutationResolver) RemoveFromCollection(ctx context.Context, collectionID string, mediaID string) (bool, error) {
	return r.repo.RemoveFromCollection(ctx, collectionID, mediaID)
}

// ReorderCollection is the resolver for the reorderCollection field.
func (r *mutationResolver) ReorderCollection(ctx context.Context, collectionID string, mediaIds []string) (bool, error) {
	return r.repo.ReorderCollection(ctx, collectionID, mediaIds)
}

// SetCollectionTags is the resolver for the setCollectionTags field.
func (r *mutationResolver) SetCollectionTags(ctx context.Context, collectionID string, tagIds []string) (*model.Collection, error) {
	return r.repo.SetCollectionTags(ctx, collectionID, tagIds)
}

// Collections is the resolver for the collections field.
func (r *queryResolver) Collections(ctx context.Context, search *string, tagID *string, origin *string, limit *int, offset *int) ([]*model.Collection, error) {
	return r.repo.ListCollections(ctx, search, tagID, origin, limit, offset)
}

// Collection is the resolver for the collection field.
func (r *queryResolver) Collection(ctx context.Context, id string) (*model.Collection, error) {
	return r.repo.GetCollection(ctx, id)
}

// CollectionMembers is the resolver for the collectionMembers field.
func (r *queryResolver) CollectionMembers(ctx context.Context, collectionID string) ([]*model.CollectionMember, error) {
	return r.repo.CollectionMembers(ctx, collectionID)
}

// CollectionIdsForMedia is the resolver for the collectionIdsForMedia field.
func (r *queryResolver) CollectionIdsForMedia(ctx context.Context, mediaID string) ([]string, error) {
	return r.repo.CollectionIdsForMedia(ctx, mediaID)
}
