package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"log"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
	"github.com/playingwithclouds/veil/internal/media"
)

// EnsureGalleryImages records a gallery visit, which fetches a stub's images
// from its origin plugin, then returns the gallery. A failed fetch still
// returns what is stored.
func (r *mutationResolver) EnsureGalleryImages(ctx context.Context, galleryID string) (*model.Gallery, error) {
	if err := r.orchestrator.VisitGallery(ctx, galleryID); err != nil {
		log.Printf("ensureGalleryImages %s: visit: %v", galleryID, err)
	}
	return r.repo.GetGallery(ctx, galleryID)
}

// Galleries is the resolver for the galleries field.
func (r *queryResolver) Galleries(ctx context.Context, limit *int, offset *int, search *string, studioID *string, performerID *string, tagID *string, sources []string) ([]*model.Gallery, error) {
	return r.repo.ListGalleries(ctx, media.EntityFilters{
		Search:      search,
		StudioID:    studioID,
		PerformerID: performerID,
		TagID:       tagID,
		Sources:     sources,
	}, limit, offset)
}

// Gallery is the resolver for the gallery field.
func (r *queryResolver) Gallery(ctx context.Context, id string) (*model.Gallery, error) {
	return r.repo.GetGallery(ctx, id)
}
