package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
	"github.com/playingwithclouds/veil/internal/media"
)

// SetImageTags is the resolver for the setImageTags field.
func (r *mutationResolver) SetImageTags(ctx context.Context, imageID string, tagIds []string) (*model.Image, error) {
	return r.repo.SetImageTags(ctx, imageID, tagIds)
}

// Images is the resolver for the images field.
func (r *queryResolver) Images(ctx context.Context, limit *int, offset *int, search *string, studioID *string, performerID *string, tagID *string, galleryID *string, sort *string) ([]*model.Image, error) {
	filters := media.EntityFilters{
		Search:      search,
		Sort:        sort,
		StudioID:    studioID,
		PerformerID: performerID,
		TagID:       tagID,
	}
	return r.repo.ListImages(ctx, filters, galleryID, limit, offset)
}

// Image is the resolver for the image field.
func (r *queryResolver) Image(ctx context.Context, id string) (*model.Image, error) {
	return r.repo.GetImage(ctx, id)
}
