package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"strings"

	"github.com/playingwithclouds/veil/internal/api/graphql/generated"
	"github.com/playingwithclouds/veil/internal/api/graphql/model"
	"github.com/playingwithclouds/veil/internal/jobs"
)

// Scene is the resolver for the scene field.
func (r *jobResolver) Scene(ctx context.Context, obj *model.Job) (*model.Scene, error) {
	if obj.Target == nil || !strings.HasPrefix(*obj.Target, "scene:") {
		return nil, nil
	}
	return r.repo.GetScene(ctx, *obj.Target)
}

// DeleteJob is the resolver for the deleteJob field.
func (r *mutationResolver) DeleteJob(ctx context.Context, id string) (bool, error) {
	if err := r.queue.Delete(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// DeleteJobsByKind is the resolver for the deleteJobsByKind field.
func (r *mutationResolver) DeleteJobsByKind(ctx context.Context, kind string) (int, error) {
	return r.queue.DeleteByKind(ctx, jobs.Kind(kind))
}

// ClearJobs is the resolver for the clearJobs field.
func (r *mutationResolver) ClearJobs(ctx context.Context) (int, error) {
	return r.queue.Clear(ctx)
}

// ReorderDownloads is the resolver for the reorderDownloads field.
func (r *mutationResolver) ReorderDownloads(ctx context.Context, jobIds []string) (bool, error) {
	if err := r.queue.Reorder(ctx, jobIds); err != nil {
		return false, err
	}
	return true, nil
}

// RetryJob is the resolver for the retryJob field.
func (r *mutationResolver) RetryJob(ctx context.Context, id string) (bool, error) {
	if err := r.queue.Retry(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// Jobs is the resolver for the jobs field.
func (r *queryResolver) Jobs(ctx context.Context) ([]*model.Job, error) {
	all, err := r.queue.All(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Job, 0, len(all))
	for _, j := range all {
		out = append(out, jobToModel(j))
	}
	return out, nil
}

// Job is the resolver for the job field.
func (r *queryResolver) Job(ctx context.Context, id string) (*model.Job, error) {
	all, err := r.queue.All(ctx)
	if err != nil {
		return nil, err
	}
	for _, j := range all {
		if j.StringID() == id {
			return jobToModel(j), nil
		}
	}
	return nil, nil
}

// Job returns generated.JobResolver implementation.
func (r *Resolver) Job() generated.JobResolver { return &jobResolver{r} }

type jobResolver struct{ *Resolver }
