package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
)

// DownloadedScenes is the resolver for the downloadedScenes field.
func (r *queryResolver) DownloadedScenes(ctx context.Context) ([]*model.Scene, error) {
	return r.repo.DownloadedScenes(ctx)
}
