package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
)

// MediaCards is the resolver for the mediaCards field.
func (r *queryResolver) MediaCards(ctx context.Context, ids []string) ([]*model.MediaCard, error) {
	return r.repo.MediaCards(ctx, ids)
}
