package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
)

// IncrementOCount is the resolver for the incrementOCount field.
func (r *mutationResolver) IncrementOCount(ctx context.Context, mediaID string) (int, error) {
	return r.repo.IncrementOCount(ctx, mediaID)
}

// DecrementOCount is the resolver for the decrementOCount field.
func (r *mutationResolver) DecrementOCount(ctx context.Context, mediaID string) (int, error) {
	return r.repo.DecrementOCount(ctx, mediaID)
}

// OCount is the resolver for the oCount field.
func (r *queryResolver) OCount(ctx context.Context, mediaID string) (int, error) {
	return r.repo.OCount(ctx, mediaID)
}
