package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
)

// UpdateObservationStatus is the resolver for the updateObservationStatus field.
func (r *mutationResolver) UpdateObservationStatus(ctx context.Context, id string, status model.ObservationStatus) (*model.Observation, error) {
	panic(fmt.Errorf("not implemented: UpdateObservationStatus - updateObservationStatus"))
}

// Observation is the resolver for the observation field.
func (r *queryResolver) Observation(ctx context.Context, id string) (*model.Observation, error) {
	panic(fmt.Errorf("not implemented: Observation - observation"))
}

// Observations is the resolver for the observations field.
func (r *queryResolver) Observations(ctx context.Context, targetID string, status *string, limit *int, offset *int) ([]*model.Observation, error) {
	panic(fmt.Errorf("not implemented: Observations - observations"))
}
