package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
	"github.com/playingwithclouds/veil/internal/media"
)

// SetPerformerFavorite is the resolver for the setPerformerFavorite field.
func (r *mutationResolver) SetPerformerFavorite(ctx context.Context, id string, favorite bool) (*model.Performer, error) {
	return r.repo.SetPerformerFavorite(ctx, id, favorite)
}

// EnrichPerformer is the resolver for the enrichPerformer field.
func (r *mutationResolver) EnrichPerformer(ctx context.Context, id string) (bool, error) {
	if err := r.orchestrator.EnqueueEnrich(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// Performers is the resolver for the performers field.
func (r *queryResolver) Performers(ctx context.Context, limit *int, offset *int, search *string, tagID *string, sort *string) ([]*model.Performer, error) {
	return r.repo.ListPerformers(ctx, media.EntityFilters{Search: search, Sort: sort, TagID: tagID}, limit, offset)
}

// Performer is the resolver for the performer field.
func (r *queryResolver) Performer(ctx context.Context, id string) (*model.Performer, error) {
	return r.repo.GetPerformer(ctx, id)
}
