package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"path/filepath"
	"strings"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
)

// TogglePlugin is the resolver for the togglePlugin field.
func (r *mutationResolver) TogglePlugin(ctx context.Context, name string, enabled bool) (bool, error) {
	r.registry.SetEnabled(name, enabled)
	// Persist the disabled set so the choice survives restarts.
	_, err := r.settings.Update(ctx, map[string]any{"disabledPlugins": r.registry.DisabledNames()})
	if err != nil {
		return false, err
	}
	return true, nil
}

// UpdatePluginSettings is the resolver for the updatePluginSettings field.
func (r *mutationResolver) UpdatePluginSettings(ctx context.Context, pluginName string, values []*model.PluginSettingValueInput) (bool, error) {
	pluginSettings := r.settings.Cached().PluginSettings
	if pluginSettings == nil {
		pluginSettings = map[string]map[string]string{}
	}
	merged := map[string]string{}
	for key, value := range pluginSettings[pluginName] {
		merged[key] = value
	}
	for _, v := range values {
		merged[v.Key] = v.Value
	}
	pluginSettings[pluginName] = merged

	if _, err := r.settings.Update(ctx, map[string]any{"pluginSettings": pluginSettings}); err != nil {
		return false, err
	}
	return true, nil
}

// InstallPlugin is the resolver for the installPlugin field.
func (r *mutationResolver) InstallPlugin(ctx context.Context, packageName string) (bool, error) {
	if _, err := r.pluginStore.Install(ctx, strings.TrimSpace(packageName)); err != nil {
		return false, err
	}
	return true, nil
}

// UninstallPlugin is the resolver for the uninstallPlugin field.
func (r *mutationResolver) UninstallPlugin(ctx context.Context, name string) (bool, error) {
	plugin, ok := r.registry.Get(name)
	if !ok {
		return false, fmt.Errorf("plugin %q not found", name)
	}
	if err := r.pluginStore.Uninstall(filepath.Base(plugin.Dir)); err != nil {
		return false, err
	}
	return true, nil
}

// UpdatePlugins is the resolver for the updatePlugins field.
func (r *mutationResolver) UpdatePlugins(ctx context.Context) ([]string, error) {
	updated, err := r.pluginStore.Update(ctx)
	if updated == nil {
		updated = []string{}
	}
	return updated, err
}

// Plugins is the resolver for the plugins field.
func (r *queryResolver) Plugins(ctx context.Context) ([]*model.Plugin, error) {
	pluginSettings := r.settings.Cached().PluginSettings
	all := r.registry.All()
	out := make([]*model.Plugin, 0, len(all))
	for _, p := range all {
		out = append(out, pluginToModel(p, r.registry.IsEnabled(p.Meta.Name), r.registry.IsAvailable(p.Meta.Name), pluginSettings[p.Meta.Name]))
	}
	return out, nil
}

// Plugin is the resolver for the plugin field.
func (r *queryResolver) Plugin(ctx context.Context, id string) (*model.Plugin, error) {
	p, ok := r.registry.Get(id)
	if !ok {
		return nil, nil
	}
	return pluginToModel(p, r.registry.IsEnabled(id), r.registry.IsAvailable(id), r.settings.Cached().PluginSettings[id]), nil
}

// PluginPackages is the resolver for the pluginPackages field.
func (r *queryResolver) PluginPackages(ctx context.Context, query *string) ([]*model.PluginPackage, error) {
	text := ""
	if query != nil {
		text = *query
	}
	packages, err := r.pluginStore.Search(ctx, text)
	if err != nil {
		return nil, err
	}
	installed, err := r.pluginStore.Installed()
	if err != nil {
		return nil, err
	}
	installedVersions := make(map[string]string, len(installed))
	for _, plugin := range installed {
		installedVersions[plugin.Manifest.Name] = plugin.Manifest.Version
	}

	out := make([]*model.PluginPackage, 0, len(packages))
	for _, found := range packages {
		out = append(out, &model.PluginPackage{
			Name:             found.Name,
			Version:          found.Version,
			Description:      strPtrIfSet(found.Description),
			InstalledVersion: strPtrIfSet(installedVersions[found.Name]),
		})
	}
	return out, nil
}
