package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
	"github.com/playingwithclouds/veil/internal/plugins"
)

// PluginCategories is the resolver for the pluginCategories field.
func (r *queryResolver) PluginCategories(ctx context.Context, plugin string, limit *int) ([]*model.PluginCategory, error) {
	p, ok := r.registry.Get(plugin)
	if !ok {
		return nil, fmt.Errorf("plugin %q not found", plugin)
	}
	result, err := r.runner.List(ctx, p, plugins.MediaTypeTag, plugins.ListArgs{Limit: derefInt(limit, 0)})
	if err != nil {
		return nil, err
	}
	out := make([]*model.PluginCategory, 0, len(result.Items))
	for _, item := range result.Items {
		poster := item.PosterPath
		var posterPtr *string
		if poster != "" {
			posterPtr = &poster
		}
		out = append(out, &model.PluginCategory{
			ID:     item.ExternalID,
			Name:   item.Title,
			URL:    item.SourceURL,
			Count:  item.Count,
			Poster: posterPtr,
		})
	}
	return out, nil
}
