package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
	"github.com/playingwithclouds/veil/internal/recommend"
)

// RecordRecommendationChoice is the resolver for the recordRecommendationChoice field.
func (r *mutationResolver) RecordRecommendationChoice(ctx context.Context, chosenMediaID string, rejectedMediaID string) (bool, error) {
	if err := r.repo.RecordPreference(ctx, chosenMediaID, rejectedMediaID); err != nil {
		return false, err
	}
	return true, nil
}

// RecordImpressions is the resolver for the recordImpressions field.
func (r *mutationResolver) RecordImpressions(ctx context.Context, impressions []*model.ImpressionInput) (int, error) {
	return r.recommender.RecordImpressions(ctx, impressionsFromInput(impressions))
}

// Recommendations is the resolver for the recommendations field.
func (r *queryResolver) Recommendations(ctx context.Context, limit *int, offset *int, refresh *bool, sources []string, minDuration *int, maxDuration *int) ([]*model.RecommendedScene, error) {
	window := recommend.DurationRange{MinSeconds: derefInt(minDuration, 0), MaxSeconds: derefInt(maxDuration, 0)}
	items, err := r.recommender.FeedWithDuration(ctx, r.registry.InactiveNames(), sources, window, derefInt(limit, defaultFeedLimit), derefInt(offset, 0), refresh != nil && *refresh)
	if err != nil {
		return nil, err
	}
	return r.recommendedScenes(ctx, items)
}

// RecommendedRows is the resolver for the recommendedRows field.
func (r *queryResolver) RecommendedRows(ctx context.Context, rowLimit *int, perRow *int) ([]*model.RecommendationRow, error) {
	rows, err := r.recommender.Rows(ctx, r.registry.InactiveNames(), derefInt(rowLimit, defaultRowLimit), derefInt(perRow, defaultPerRow))
	if err != nil {
		return nil, err
	}
	out := make([]*model.RecommendationRow, 0, len(rows))
	for _, row := range rows {
		converted, err := r.recommendationRow(ctx, row)
		if err != nil {
			return nil, err
		}
		out = append(out, converted)
	}
	return out, nil
}

// RecommendedCategories is the resolver for the recommendedCategories field.
func (r *queryResolver) RecommendedCategories(ctx context.Context, categoryLimit *int, perCategory *int) ([]*model.RecommendedCategory, error) {
	categories, err := r.recommender.Categories(ctx, r.registry.InactiveNames(), derefInt(categoryLimit, defaultCategoryLimit), derefInt(perCategory, defaultPerCategory))
	if err != nil {
		return nil, err
	}
	out := make([]*model.RecommendedCategory, 0, len(categories))
	for _, category := range categories {
		converted, err := r.recommendedCategory(ctx, category)
		if err != nil {
			return nil, err
		}
		if converted != nil {
			out = append(out, converted)
		}
	}
	return out, nil
}

// RecommendationPair is the resolver for the recommendationPair field.
func (r *queryResolver) RecommendationPair(ctx context.Context) ([]*model.Scene, error) {
	items, err := r.recommender.Pair(ctx, r.registry.InactiveNames())
	if err != nil {
		return nil, err
	}
	scenes, err := r.repo.ScenesByIDs(ctx, itemSceneIDs(items))
	if err != nil || len(scenes) != 2 {
		return []*model.Scene{}, err
	}
	return scenes, nil
}
