package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
	"github.com/playingwithclouds/veil/internal/media"
)

// CreateSavedFilter is the resolver for the createSavedFilter field.
func (r *mutationResolver) CreateSavedFilter(ctx context.Context, name string, filter model.SceneFilterInput) (*model.SavedFilter, error) {
	return r.repo.CreateSavedFilter(ctx, name, media.SavedFilterInput{
		Search:      filter.Search,
		StudioID:    filter.StudioID,
		PerformerID: filter.PerformerID,
		TagID:       filter.TagID,
		MinRating:   filter.MinRating,
		MinDuration: filter.MinDuration,
		MaxDuration: filter.MaxDuration,
		DateFrom:    filter.DateFrom,
		DateTo:      filter.DateTo,
		Sort:        filter.Sort,
	})
}

// DeleteSavedFilter is the resolver for the deleteSavedFilter field.
func (r *mutationResolver) DeleteSavedFilter(ctx context.Context, filterID string) (bool, error) {
	return r.repo.DeleteSavedFilter(ctx, filterID)
}

// SavedFilters is the resolver for the savedFilters field.
func (r *queryResolver) SavedFilters(ctx context.Context) ([]*model.SavedFilter, error) {
	return r.repo.ListSavedFilters(ctx)
}
