package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"bytes"
	"context"
	"encoding/base64"
	"fmt"
	"strings"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
)

// RecordSceneHeat is the resolver for the recordSceneHeat field.
func (r *mutationResolver) RecordSceneHeat(ctx context.Context, input model.RecordSceneHeatInput) (bool, error) {
	if err := r.repo.RecordSceneHeat(ctx, input); err != nil {
		return false, err
	}
	return true, nil
}

// SetSceneThumbnail is the resolver for the setSceneThumbnail field.
func (r *mutationResolver) SetSceneThumbnail(ctx context.Context, sceneID string, atSeconds float64, jpegBase64 string) (bool, error) {
	if r.blobStore == nil {
		return false, fmt.Errorf("blob store not configured")
	}
	frame, err := base64.StdEncoding.DecodeString(jpegBase64)
	if err != nil {
		return false, fmt.Errorf("thumbnail is not base64: %w", err)
	}
	// The moment is in the key so a new frame gets a new URL and clients do not keep the old image.
	key := fmt.Sprintf("images/scene-thumbnails/%s-%d.jpg", strings.ReplaceAll(sceneID, ":", "-"), int(atSeconds))
	if err := r.blobStore.Put(ctx, key, bytes.NewReader(frame), int64(len(frame)), "image/jpeg"); err != nil {
		return false, fmt.Errorf("store thumbnail: %w", err)
	}
	if err := r.repo.SetSceneThumbnail(ctx, sceneID, r.blobStore.DirectURL(key), atSeconds); err != nil {
		return false, err
	}
	return true, nil
}

// SceneHeat is the resolver for the sceneHeat field.
func (r *queryResolver) SceneHeat(ctx context.Context, sceneID string) (*model.SceneHeat, error) {
	return r.repo.SceneHeat(ctx, sceneID)
}
