package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/playingwithclouds/veil/internal/api/graphql/generated"
	"github.com/playingwithclouds/veil/internal/api/graphql/model"
	"github.com/playingwithclouds/veil/internal/media"
)

// Scenes is the resolver for the scenes field.
func (r *queryResolver) Scenes(ctx context.Context, limit *int, offset *int, search *string, studioID *string, performerID *string, tagID *string, sort *string, minRating *float64, minDuration *int, maxDuration *int, dateFrom *string, dateTo *string, sources []string, includeTagIds []string, excludeTagIds []string) ([]*model.Scene, error) {
	return r.repo.ListScenes(ctx, media.EntityFilters{
		Search:          search,
		Sort:            sort,
		StudioID:        studioID,
		PerformerID:     performerID,
		TagID:           tagID,
		MinRating:       minRating,
		MinDuration:     minDuration,
		MaxDuration:     maxDuration,
		DateFrom:        dateFrom,
		DateTo:          dateTo,
		DisabledPlugins: r.registry.InactiveNames(),
		Sources:         sources,
		IncludeTagIDs:   includeTagIds,
		ExcludeTagIDs:   excludeTagIds,
	}, limit, offset)
}

// Scene is the resolver for the scene field.
func (r *queryResolver) Scene(ctx context.Context, id string) (*model.Scene, error) {
	return r.repo.GetScene(ctx, id)
}

// RandomScenes is the resolver for the randomScenes field.
func (r *queryResolver) RandomScenes(ctx context.Context, limit *int) ([]*model.Scene, error) {
	return r.repo.RandomScenes(ctx, derefInt(limit, 5), media.EntityFilters{
		DisabledPlugins: r.registry.InactiveNames(),
	})
}

// RecommendedFeed is the resolver for the recommendedFeed field: the ranked
// feed without reasons.
func (r *queryResolver) RecommendedFeed(ctx context.Context, limit *int, offset *int) ([]*model.Scene, error) {
	items, err := r.recommender.Feed(ctx, r.registry.InactiveNames(), nil, derefInt(limit, defaultFeedLimit), derefInt(offset, 0), false)
	if err != nil {
		return nil, err
	}
	return r.repo.ScenesByIDs(ctx, itemSceneIDs(items))
}

// Related is the resolver for the related field.
func (r *sceneResolver) Related(ctx context.Context, obj *model.Scene, limit *int) ([]*model.Scene, error) {
	return r.repo.RelatedScenes(ctx, obj.ID, derefInt(limit, 24), r.registry.InactiveNames())
}

// Scene returns generated.SceneResolver implementation.
func (r *Resolver) Scene() generated.SceneResolver { return &sceneResolver{r} }

type sceneResolver struct{ *Resolver }
