package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
)

// CreateSceneMarker is the resolver for the createSceneMarker field.
func (r *mutationResolver) CreateSceneMarker(ctx context.Context, mediaID string, seconds float64, endSeconds *float64, tagName *string, label *string) (*model.SceneMarker, error) {
	return r.repo.CreateSceneMarker(ctx, mediaID, seconds, endSeconds, tagName, label)
}

// DeleteSceneMarker is the resolver for the deleteSceneMarker field.
func (r *mutationResolver) DeleteSceneMarker(ctx context.Context, markerID string) (bool, error) {
	return r.repo.DeleteSceneMarker(ctx, markerID)
}

// SceneMarkers is the resolver for the sceneMarkers field.
func (r *queryResolver) SceneMarkers(ctx context.Context, mediaID string) ([]*model.SceneMarker, error) {
	return r.repo.SceneMarkers(ctx, mediaID)
}
