package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
	"github.com/playingwithclouds/veil/internal/suggest"
)

// RecordSearch is the resolver for the recordSearch field.
func (r *mutationResolver) RecordSearch(ctx context.Context, query string) (bool, error) {
	return r.suggestions.RecordSearch(ctx, query)
}

// ForgetSearch is the resolver for the forgetSearch field.
func (r *mutationResolver) ForgetSearch(ctx context.Context, query string) (bool, error) {
	return r.suggestions.ForgetSearch(ctx, query)
}

// SearchSuggestions is the resolver for the searchSuggestions field.
func (r *queryResolver) SearchSuggestions(ctx context.Context, query string, limit *int) ([]*model.SearchSuggestion, error) {
	suggestions, err := r.suggestions.Suggest(ctx, query, derefInt(limit, suggest.DefaultLimit))
	if err != nil {
		return nil, err
	}
	return searchSuggestionModels(suggestions), nil
}
