package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"
	"log"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
	"github.com/playingwithclouds/veil/internal/plugins"
)

// ResolvePluginResult synchronously scrapes a source URL and ingests the full
// record, returning its canonical id. Unlike the async `scrape` mutation (which
// only queues a job), this blocks so the caller can open a populated detail page.
func (r *mutationResolver) ResolvePluginResult(ctx context.Context, pluginName string, url string, posterURL *string) (string, error) {
	plugin, ok := r.registry.Get(pluginName)
	if !ok {
		return "", fmt.Errorf("plugin %q not found", pluginName)
	}

	entity, ok := plugin.ContentFindEntity()
	if !ok {
		return "", fmt.Errorf("plugin %q has no find capability", pluginName)
	}
	results, err := r.runner.Find(ctx, plugin, entity, url)
	if err != nil {
		return "", err
	}

	// Some sources expose the poster only on the browse listing, not the detail
	// page. Backfill it from the caller so the record has an image.
	if posterURL != nil && *posterURL != "" {
		for _, result := range results {
			if result.Scene != nil && result.Scene.PosterPath == "" {
				result.Scene.PosterPath = *posterURL
			}
		}
	}

	ingestResult, err := r.ingestSvc.IngestScrapeResults(ctx, pluginName, url, results)
	if err != nil {
		return "", err
	}
	if ingestResult == nil || ingestResult.CanonicalID == "" {
		return "", fmt.Errorf("scrape produced no media record")
	}
	return ingestResult.CanonicalID, nil
}

// AttachAlikeSource is the resolver for the attachAlikeSource field.
func (r *mutationResolver) AttachAlikeSource(ctx context.Context, sceneID string, pluginName string, url string) ([]*model.Stream, error) {
	return r.attachAlikeSource(ctx, sceneID, pluginName, url)
}

// EnsureEntityScenes fetches a studio's or performer's scenes from every
// scene plugin when its page opens, at most once per day.
func (r *mutationResolver) EnsureEntityScenes(ctx context.Context, entityID string) (int, error) {
	if r.entityScenes == nil {
		return 0, fmt.Errorf("entity scene fetching is not available")
	}
	return r.entityScenes.Ensure(ctx, entityID)
}

// PluginSearch backs live search: it fans out to every enabled
// search-capable plugin and returns their raw results (banner + preview frames)
// without touching the database. Selecting a result ingests it via the scrape mutation.
func (r *queryResolver) PluginSearch(ctx context.Context, query string, limit *int, pluginNames []string) ([]*model.PluginSearchResult, error) {
	if query == "" {
		return []*model.PluginSearchResult{}, nil
	}
	max := 20
	if limit != nil && *limit > 0 {
		max = *limit
	}

	// NSFW search only queries adult sources; SFW plugins never leak in.
	searchPlugins := adultPlugins(r.registry.WithAnyCapability(plugins.CapabilitySceneList, plugins.CapabilityGalleryList))
	searchPlugins = filterPluginsByName(searchPlugins, pluginNames)
	if len(searchPlugins) == 0 {
		return []*model.PluginSearchResult{}, nil
	}

	collected := r.fanOutSearch(ctx, searchPlugins, query, max)

	seen := make(map[string]bool)
	results := make([]*model.PluginSearchResult, 0, len(collected))
	toPersist := make([]discoveredItemWithPlugin, 0, len(collected))
	for _, entry := range collected {
		if seen[entry.item.ExternalID] {
			continue
		}
		seen[entry.item.ExternalID] = true
		results = append(results, pluginSearchResult(entry.plugin, entry.item))
		toPersist = append(toPersist, entry)
	}
	r.persistDiscoveredItems(toPersist)
	r.logSearch(query, pluginNames, len(results))
	return results, nil
}

// PluginBrowse backs the NSFW landing feed: the latest items from every enabled
// scene:list-capable plugin, mapped like search results.
func (r *queryResolver) PluginBrowse(ctx context.Context, limit *int, offset *int) ([]*model.PluginSearchResult, error) {
	max := 40
	if limit != nil && *limit > 0 {
		max = *limit
	}
	skip := 0
	if offset != nil && *offset > 0 {
		skip = *offset
	}

	browsePlugins := adultPlugins(r.registry.WithAnyCapability(plugins.CapabilitySceneList, plugins.CapabilityGalleryList))
	if len(browsePlugins) == 0 {
		return []*model.PluginSearchResult{}, nil
	}

	type pluginResult struct {
		name  string
		items []plugins.DiscoveredItem
	}
	ch := make(chan pluginResult, len(browsePlugins))

	for _, plugin := range browsePlugins {
		go func(plugin *plugins.Plugin) {
			entity, ok := plugin.ContentListEntity()
			if !ok {
				ch <- pluginResult{name: plugin.Meta.Name}
				return
			}
			result, err := r.runner.List(ctx, plugin, entity, plugins.ListArgs{Limit: max, Offset: skip})
			if err != nil {
				log.Printf("pluginBrowse via %s: %v", plugin.Meta.Name, err)
				ch <- pluginResult{name: plugin.Meta.Name}
				return
			}
			ch <- pluginResult{name: plugin.Meta.Name, items: result.Items}
		}(plugin)
	}

	seen := make(map[string]bool)
	results := make([]*model.PluginSearchResult, 0, len(browsePlugins)*max)
	toPersist := make([]discoveredItemWithPlugin, 0, len(browsePlugins)*max)
	for range browsePlugins {
		res := <-ch
		for _, item := range res.items {
			if seen[item.ExternalID] {
				continue
			}
			seen[item.ExternalID] = true
			results = append(results, pluginSearchResult(res.name, item))
			toPersist = append(toPersist, discoveredItemWithPlugin{plugin: res.name, item: item})
		}
	}
	r.persistDiscoveredItems(toPersist)
	return results, nil
}

// RecommendedBrowse is the resolver for the recommendedBrowse field.
func (r *queryResolver) RecommendedBrowse(ctx context.Context, limit *int) ([]*model.PluginSearchResult, error) {
	return r.runRecommendedBrowse(ctx, limit)
}

// FindAlikeSources is the resolver for the findAlikeSources field.
func (r *queryResolver) FindAlikeSources(ctx context.Context, sceneID string, limit *int) ([]*model.AlikeCandidate, error) {
	return r.findAlikeSources(ctx, sceneID, limit)
}
