package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
)

// UpdateSettings is the resolver for the updateSettings field.
func (r *mutationResolver) UpdateSettings(ctx context.Context, input model.UpdateSettingsInput) (*model.Settings, error) {
	updates := map[string]any{}
	if input.MaxConcurrentJobs != nil {
		updates["maxConcurrentJobs"] = *input.MaxConcurrentJobs
	}
	if input.MaxJobRetries != nil {
		updates["maxJobRetries"] = *input.MaxJobRetries
	}
	if input.DownloadSpeedLimitKBps != nil {
		updates["downloadSpeedLimitKBps"] = *input.DownloadSpeedLimitKBps
	}
	if input.AllowDownloadsWhileStreaming != nil {
		updates["allowDownloadsWhileStreaming"] = *input.AllowDownloadsWhileStreaming
	}
	if input.AutoEnrichAfterScrape != nil {
		updates["autoEnrichAfterScrape"] = *input.AutoEnrichAfterScrape
	}
	if input.RequireVpn != nil {
		updates["requireVpn"] = *input.RequireVpn
	}
	if input.KindLimits != nil {
		updates["kindLimits"] = mergeKindLimits(r.settings.Cached().KindLimits, input.KindLimits)
	}

	updated, err := r.settings.Update(ctx, updates)
	if err != nil {
		return nil, err
	}
	return settingsToModel(updated), nil
}

// UpsertSettingEntry is the resolver for the upsertSettingEntry field.
func (r *mutationResolver) UpsertSettingEntry(ctx context.Context, input model.UpsertSettingEntryInput) (*model.SettingEntry, error) {
	panic(fmt.Errorf("not implemented: UpsertSettingEntry - upsertSettingEntry"))
}

// DeleteSettingEntry is the resolver for the deleteSettingEntry field.
func (r *mutationResolver) DeleteSettingEntry(ctx context.Context, id string) (bool, error) {
	panic(fmt.Errorf("not implemented: DeleteSettingEntry - deleteSettingEntry"))
}

// Settings is the resolver for the settings field.
func (r *queryResolver) Settings(ctx context.Context) (*model.Settings, error) {
	current, err := r.settings.Get(ctx)
	if err != nil {
		return nil, err
	}
	return settingsToModel(current), nil
}

// SettingEntries is the resolver for the settingEntries field.
func (r *queryResolver) SettingEntries(ctx context.Context, scope *string) ([]*model.SettingEntry, error) {
	panic(fmt.Errorf("not implemented: SettingEntries - settingEntries"))
}
