package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"log"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
)

// CreateStream is the resolver for the createStream field.
func (r *mutationResolver) CreateStream(ctx context.Context, input model.CreateStreamInput) (*model.Stream, error) {
	return r.repo.CreateStream(ctx, input)
}

// DeleteStream is the resolver for the deleteStream field.
func (r *mutationResolver) DeleteStream(ctx context.Context, id string) (bool, error) {
	return r.repo.DeleteStream(ctx, id)
}

// EnsureSceneStreams is called when a scene page opens. It records the visit —
// the first one fetches the scene's detail page (details, streams, the site's
// related list), and related scenes are topped up in the background — then
// returns the ranked streams. A failed fetch still returns what is stored.
func (r *mutationResolver) EnsureSceneStreams(ctx context.Context, sceneID string) ([]*model.Stream, error) {
	if err := r.orchestrator.VisitScene(ctx, sceneID); err != nil {
		log.Printf("ensureSceneStreams %s: visit: %v", sceneID, err)
	}
	return r.loadRankedStreams(ctx, sceneID)
}

// MediaStreams is the resolver for the mediaStreams field.
func (r *queryResolver) MediaStreams(ctx context.Context, mediaID string) ([]*model.Stream, error) {
	streams, err := r.repo.ListStreams(ctx, mediaID)
	if err != nil {
		return nil, err
	}
	r.rankStreams(streams)
	return streams, nil
}
