package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
	"github.com/playingwithclouds/veil/internal/media"
)

// SetStudioTags is the resolver for the setStudioTags field.
func (r *mutationResolver) SetStudioTags(ctx context.Context, studioID string, tagIds []string) (*model.Studio, error) {
	return r.repo.SetStudioTags(ctx, studioID, tagIds)
}

// Studios is the resolver for the studios field.
func (r *queryResolver) Studios(ctx context.Context, limit *int, offset *int, search *string, tagID *string, sort *string) ([]*model.Studio, error) {
	return r.repo.ListStudios(ctx, media.EntityFilters{Search: search, Sort: sort, TagID: tagID}, limit, offset)
}

// Studio is the resolver for the studio field.
func (r *queryResolver) Studio(ctx context.Context, id string) (*model.Studio, error) {
	return r.repo.GetStudio(ctx, id)
}
