package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"

	"github.com/playingwithclouds/veil/internal/api/graphql/generated"
	"github.com/playingwithclouds/veil/internal/api/graphql/model"
	"github.com/playingwithclouds/veil/internal/media"
)

// SubscribeSearch is the resolver for the subscribeSearch field.
func (r *mutationResolver) SubscribeSearch(ctx context.Context, query string, sources []string, intervalHours *int) (*model.SearchSubscription, error) {
	interval := 0
	if intervalHours != nil {
		interval = *intervalHours
	}
	subscription, created, err := r.repo.SubscribeSearch(ctx, query, sources, interval)
	if err != nil {
		return nil, err
	}
	if created {
		r.searchRuns.RunInBackground(subscription)
	}
	return subscription, nil
}

// Subscribe is the resolver for the subscribe field.
func (r *mutationResolver) Subscribe(ctx context.Context, kind model.SubscriptionKind, targetID string, intervalHours *int) (*model.SearchSubscription, error) {
	subscription, created, err := r.repo.SubscribeEntity(ctx, kind, targetID, derefInt(intervalHours, 0))
	if err != nil {
		return nil, err
	}
	if created {
		r.searchRuns.RunInBackground(subscription)
	}
	return subscription, nil
}

// UpdateSearchSubscription is the resolver for the updateSearchSubscription field.
func (r *mutationResolver) UpdateSearchSubscription(ctx context.Context, id string, intervalHours *int, enabled *bool) (*model.SearchSubscription, error) {
	return r.repo.UpdateSearchSubscription(ctx, id, intervalHours, enabled)
}

// UnsubscribeSearch is the resolver for the unsubscribeSearch field.
func (r *mutationResolver) UnsubscribeSearch(ctx context.Context, id string) (bool, error) {
	if err := r.repo.DeleteSearchSubscription(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// RunSearchSubscription is the resolver for the runSearchSubscription field.
func (r *mutationResolver) RunSearchSubscription(ctx context.Context, id string) (*model.SearchSubscription, error) {
	subscription, err := r.repo.SearchSubscription(ctx, id)
	if err != nil {
		return nil, err
	}
	if err := r.searchRuns.Run(ctx, subscription); err != nil {
		return nil, err
	}
	return r.repo.SearchSubscription(ctx, id)
}

// MarkSearchSubscriptionSeen is the resolver for the markSearchSubscriptionSeen field.
func (r *mutationResolver) MarkSearchSubscriptionSeen(ctx context.Context, id string) (*model.SearchSubscription, error) {
	return r.repo.MarkSearchSubscriptionSeen(ctx, id)
}

// SearchSubscriptions is the resolver for the searchSubscriptions field.
func (r *queryResolver) SearchSubscriptions(ctx context.Context) ([]*model.SearchSubscription, error) {
	return r.repo.SearchSubscriptions(ctx)
}

// SearchSubscription is the resolver for the searchSubscription field.
func (r *queryResolver) SearchSubscription(ctx context.Context, id string) (*model.SearchSubscription, error) {
	subscription, err := r.repo.SearchSubscription(ctx, id)
	if errors.Is(err, media.ErrSearchSubscriptionNotFound) {
		return nil, nil
	}
	return subscription, err
}

// SubscriptionForTarget is the resolver for the subscriptionForTarget field.
func (r *queryResolver) SubscriptionForTarget(ctx context.Context, targetID string) (*model.SearchSubscription, error) {
	subscription, err := r.repo.SubscriptionForTarget(ctx, targetID)
	if errors.Is(err, media.ErrSearchSubscriptionNotFound) {
		return nil, nil
	}
	return subscription, err
}

// SubscriptionFeed is the resolver for the subscriptionFeed field.
func (r *queryResolver) SubscriptionFeed(ctx context.Context, filter *model.SubscriptionFeedFilter, limit *int, offset *int) ([]*model.SubscriptionFeedItem, error) {
	return r.repo.SubscriptionFeed(ctx, filter, derefInt(limit, 48), derefInt(offset, 0), r.registry.InactiveNames())
}

// NewCount is the resolver for the newCount field.
func (r *searchSubscriptionResolver) NewCount(ctx context.Context, obj *model.SearchSubscription) (int, error) {
	_, unseen, err := r.repo.SearchSubscriptionSceneCounts(ctx, obj.ID, r.registry.InactiveNames())
	return unseen, err
}

// TotalCount is the resolver for the totalCount field.
func (r *searchSubscriptionResolver) TotalCount(ctx context.Context, obj *model.SearchSubscription) (int, error) {
	total, _, err := r.repo.SearchSubscriptionSceneCounts(ctx, obj.ID, r.registry.InactiveNames())
	return total, err
}

// Scenes is the resolver for the scenes field.
func (r *searchSubscriptionResolver) Scenes(ctx context.Context, obj *model.SearchSubscription, limit *int, offset *int) ([]*model.Scene, error) {
	return r.repo.SearchSubscriptionScenes(ctx, obj.ID, derefInt(limit, 48), derefInt(offset, 0), r.registry.InactiveNames())
}

// SearchSubscription returns generated.SearchSubscriptionResolver implementation.
func (r *Resolver) SearchSubscription() generated.SearchSubscriptionResolver {
	return &searchSubscriptionResolver{r}
}

type searchSubscriptionResolver struct{ *Resolver }
