package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
)

// UpsertUserRating is the resolver for the upsertUserRating field.
func (r *mutationResolver) UpsertUserRating(ctx context.Context, input model.UpsertUserRatingInput) (*model.UserRating, error) {
	return r.repo.UpsertUserRating(ctx, input)
}

// DeleteUserRating is the resolver for the deleteUserRating field.
func (r *mutationResolver) DeleteUserRating(ctx context.Context, mediaID string) (bool, error) {
	return r.repo.DeleteUserRating(ctx, mediaID)
}

// UserRating is the resolver for the userRating field.
func (r *queryResolver) UserRating(ctx context.Context, mediaID string) (*model.UserRating, error) {
	return r.repo.UserRating(ctx, mediaID)
}

// UserRatings is the resolver for the userRatings field.
func (r *queryResolver) UserRatings(ctx context.Context, limit *int, offset *int) ([]*model.UserRating, error) {
	return r.repo.ListUserRatings(ctx, limit, offset)
}
