package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/playingwithclouds/veil/internal/api/graphql/generated"
	"github.com/playingwithclouds/veil/internal/api/graphql/model"
)

// UpsertWatchHistory is the resolver for the upsertWatchHistory field.
func (r *mutationResolver) UpsertWatchHistory(ctx context.Context, input model.UpsertWatchHistoryInput) (*model.WatchHistory, error) {
	return r.repo.UpsertWatchHistory(ctx, input)
}

// DeleteWatchHistory is the resolver for the deleteWatchHistory field.
func (r *mutationResolver) DeleteWatchHistory(ctx context.Context, mediaID string) (bool, error) {
	return r.repo.DeleteWatchHistory(ctx, mediaID)
}

// WatchHistory is the resolver for the watchHistory field.
func (r *queryResolver) WatchHistory(ctx context.Context, limit *int, offset *int) ([]*model.WatchHistory, error) {
	return r.repo.ListWatchHistory(ctx, limit, offset)
}

// WatchHistoryEntry is the resolver for the watchHistoryEntry field.
func (r *queryResolver) WatchHistoryEntry(ctx context.Context, mediaID string) (*model.WatchHistory, error) {
	return r.repo.WatchHistoryEntry(ctx, mediaID)
}

// Scene is the resolver for the scene field.
func (r *watchHistoryResolver) Scene(ctx context.Context, obj *model.WatchHistory) (*model.Scene, error) {
	if obj.Media == "" {
		return nil, nil
	}
	return r.repo.GetScene(ctx, obj.Media)
}

// WatchHistory returns generated.WatchHistoryResolver implementation.
func (r *Resolver) WatchHistory() generated.WatchHistoryResolver { return &watchHistoryResolver{r} }

type watchHistoryResolver struct{ *Resolver }
