package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/playingwithclouds/veil/internal/api/graphql/model"
)

// AddToWatchlist is the resolver for the addToWatchlist field.
func (r *mutationResolver) AddToWatchlist(ctx context.Context, mediaID string) (*model.WatchlistItem, error) {
	return r.repo.AddToWatchlist(ctx, mediaID)
}

// RemoveFromWatchlist is the resolver for the removeFromWatchlist field.
func (r *mutationResolver) RemoveFromWatchlist(ctx context.Context, mediaID string) (bool, error) {
	return r.repo.RemoveFromWatchlist(ctx, mediaID)
}

// Watchlist is the resolver for the watchlist field.
func (r *queryResolver) Watchlist(ctx context.Context) ([]*model.WatchlistItem, error) {
	return r.repo.ListWatchlist(ctx)
}
