// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AlikeCandidate struct {
	ExternalID      string   `json:"externalId"`
	Title           string   `json:"title"`
	Plugin          string   `json:"plugin"`
	SourceURL       string   `json:"sourceUrl"`
	PosterURL       *string  `json:"posterUrl,omitempty"`
	Date            *string  `json:"date,omitempty"`
	PreviewImages   []string `json:"previewImages"`
	PreviewVideo    *string  `json:"previewVideo,omitempty"`
	DurationSeconds *int     `json:"durationSeconds,omitempty"`
	MatchScore      float64  `json:"matchScore"`
}

type BlocklistEntry struct {
	ID        string  `json:"id"`
	Kind      string  `json:"kind"`
	TargetID  string  `json:"targetId"`
	Label     *string `json:"label,omitempty"`
	CreatedAt string  `json:"createdAt"`
}

type Change struct {
	ID            string  `json:"id"`
	Canonical     string  `json:"canonical"`
	Observation   string  `json:"observation"`
	Plugin        string  `json:"plugin"`
	Key           string  `json:"key"`
	Action        string  `json:"action"`
	Value         *string `json:"value,omitempty"`
	OriginalValue *string `json:"originalValue,omitempty"`
	Iso6391       *string `json:"iso6391,omitempty"`
	Iso31661      *string `json:"iso31661,omitempty"`
	Score         float64 `json:"score"`
	Mode          string  `json:"mode"`
	ChangedBy     *string `json:"changedBy,omitempty"`
	CreatedAt     string  `json:"createdAt"`
}

type Collection struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Details    *string `json:"details,omitempty"`
	CoverPath  *string `json:"coverPath,omitempty"`
	ItemCount  int     `json:"itemCount"`
	Origin     string  `json:"origin"`
	SourceURL  *string `json:"sourceUrl,omitempty"`
	ExternalID *string `json:"externalId,omitempty"`
	Tags       []*Tag  `json:"tags"`
	CreatedAt  string  `json:"createdAt"`
	UpdatedAt  string  `json:"updatedAt"`
}

type CollectionMember struct {
	MediaID    string  `json:"mediaId"`
	MediaType  string  `json:"mediaType"`
	Position   int     `json:"position"`
	Title      string  `json:"title"`
	PosterPath *string `json:"posterPath,omitempty"`
}

type CreateStreamInput struct {
	MediaID          string   `json:"mediaId"`
	URL              string   `json:"url"`
	Kind             *string  `json:"kind,omitempty"`
	Label            *string  `json:"label,omitempty"`
	Provider         *string  `json:"provider,omitempty"`
	Resolution       *string  `json:"resolution,omitempty"`
	Width            *int     `json:"width,omitempty"`
	Height           *int     `json:"height,omitempty"`
	Language         *string  `json:"language,omitempty"`
	Format           *string  `json:"format,omitempty"`
	MimeType         *string  `json:"mimeType,omitempty"`
	ExpectedSpeedBps *float64 `json:"expectedSpeedBps,omitempty"`
	FileSizeBytes    *float64 `json:"fileSizeBytes,omitempty"`
	Verified         *bool    `json:"verified,omitempty"`
	PluginName       *string  `json:"pluginName,omitempty"`
}

type Gallery struct {
	ID         string       `json:"id"`
	ExternalID string       `json:"externalId"`
	SourceURL  string       `json:"sourceUrl"`
	Title      string       `json:"title"`
	Details    *string      `json:"details,omitempty"`
	Date       *string      `json:"date,omitempty"`
	CoverPath  *string      `json:"coverPath,omitempty"`
	ImageCount int          `json:"imageCount"`
	Rating     *float64     `json:"rating,omitempty"`
	Organized  bool         `json:"organized"`
	Studio     *Studio      `json:"studio,omitempty"`
	Performers []*Performer `json:"performers"`
	Tags       []*Tag       `json:"tags"`
	Images     []*Image     `json:"images"`
	TagMatch   *string      `json:"tagMatch,omitempty"`
	CreatedAt  string       `json:"createdAt"`
	UpdatedAt  string       `json:"updatedAt"`
}

type HeatSpanInput struct {
	FromSeconds float64 `json:"fromSeconds"`
	ToSeconds   float64 `json:"toSeconds"`
}

type Image struct {
	ID         string       `json:"id"`
	FilePath   string       `json:"filePath"`
	Title      *string      `json:"title,omitempty"`
	Details    *string      `json:"details,omitempty"`
	Date       *string      `json:"date,omitempty"`
	SourceURL  *string      `json:"sourceUrl,omitempty"`
	ExternalID *string      `json:"externalId,omitempty"`
	Width      *int         `json:"width,omitempty"`
	Height     *int         `json:"height,omitempty"`
	Position   *int         `json:"position,omitempty"`
	Rating     *float64     `json:"rating,omitempty"`
	Organized  bool         `json:"organized"`
	GalleryID  *string      `json:"galleryId,omitempty"`
	Studio     *Studio      `json:"studio,omitempty"`
	Performers []*Performer `json:"performers"`
	Tags       []*Tag       `json:"tags"`
	TagMatch   *string      `json:"tagMatch,omitempty"`
	CreatedAt  string       `json:"createdAt"`
	UpdatedAt  string       `json:"updatedAt"`
}

type ImpressionInput struct {
	MediaID  string  `json:"mediaId"`
	Source   *string `json:"source,omitempty"`
	Surface  *string `json:"surface,omitempty"`
	Position *int    `json:"position,omitempty"`
	Clicked  *bool   `json:"clicked,omitempty"`
}

type Job struct {
	ID                    string   `json:"id"`
	Kind                  string   `json:"kind"`
	Status                string   `json:"status"`
	Title                 *string  `json:"title,omitempty"`
	Description           *string  `json:"description,omitempty"`
	PluginName            string   `json:"pluginName"`
	Target                *string  `json:"target,omitempty"`
	Error                 *string  `json:"error,omitempty"`
	Attempts              int      `json:"attempts"`
	MaxAttempts           int      `json:"maxAttempts"`
	Priority              int      `json:"priority"`
	RunAt                 *string  `json:"runAt,omitempty"`
	StartedAt             *string  `json:"startedAt,omitempty"`
	FinishedAt            *string  `json:"finishedAt,omitempty"`
	CreatedAt             string   `json:"createdAt"`
	UpdatedAt             string   `json:"updatedAt"`
	DownloadTitle         *string  `json:"downloadTitle,omitempty"`
	DownloadURL           *string  `json:"downloadUrl,omitempty"`
	DownloadProgress      *float64 `json:"downloadProgress,omitempty"`
	DownloadBytesReceived *float64 `json:"downloadBytesReceived,omitempty"`
	DownloadBytesTotal    *float64 `json:"downloadBytesTotal,omitempty"`
	Scene                 *Scene   `json:"scene,omitempty"`
}

type KindRateLimit struct {
	Kind            string  `json:"kind"`
	MaxConcurrent   int     `json:"maxConcurrent"`
	RetryInitialMs  int     `json:"retryInitialMs"`
	RetryMultiplier float64 `json:"retryMultiplier"`
	RetryMaxMs      int     `json:"retryMaxMs"`
}

type KindRateLimitInput struct {
	Kind            string   `json:"kind"`
	MaxConcurrent   *int     `json:"maxConcurrent,omitempty"`
	RetryInitialMs  *int     `json:"retryInitialMs,omitempty"`
	RetryMultiplier *float64 `json:"retryMultiplier,omitempty"`
	RetryMaxMs      *int     `json:"retryMaxMs,omitempty"`
}

type MediaCard struct {
	MediaID      string  `json:"mediaId"`
	MediaType    string  `json:"mediaType"`
	Title        string  `json:"title"`
	PosterPath   *string `json:"posterPath,omitempty"`
	BackdropPath *string `json:"backdropPath,omitempty"`
}

type MediaEvent struct {
	ID    string `json:"id"`
	Type  string `json:"type"`
	Title string `json:"title"`
}

type Mutation struct {
}

type Observation struct {
	ID         string            `json:"id"`
	Target     string            `json:"target"`
	Plugin     string            `json:"plugin"`
	SourceURL  string            `json:"sourceUrl"`
	Confidence float64           `json:"confidence"`
	Status     ObservationStatus `json:"status"`
	Data       *string           `json:"data,omitempty"`
	Job        *string           `json:"job,omitempty"`
	ObservedAt string            `json:"observedAt"`
}

type Performer struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	Aliases      []string `json:"aliases"`
	Details      *string  `json:"details,omitempty"`
	Gender       *string  `json:"gender,omitempty"`
	Birthdate    *string  `json:"birthdate,omitempty"`
	DeathDate    *string  `json:"deathDate,omitempty"`
	Country      *string  `json:"country,omitempty"`
	Ethnicity    *string  `json:"ethnicity,omitempty"`
	EyeColor     *string  `json:"eyeColor,omitempty"`
	HairColor    *string  `json:"hairColor,omitempty"`
	HeightCm     *int     `json:"heightCm,omitempty"`
	WeightKg     *int     `json:"weightKg,omitempty"`
	Measurements *string  `json:"measurements,omitempty"`
	FakeTits     *string  `json:"fakeTits,omitempty"`
	Tattoos      *string  `json:"tattoos,omitempty"`
	Piercings    *string  `json:"piercings,omitempty"`
	CareerLength *string  `json:"careerLength,omitempty"`
	URL          *string  `json:"url,omitempty"`
	Twitter      *string  `json:"twitter,omitempty"`
	Instagram    *string  `json:"instagram,omitempty"`
	ImagePath    *string  `json:"imagePath,omitempty"`
	Favorite     bool     `json:"favorite"`
	Rating       *float64 `json:"rating,omitempty"`
	Tags         []*Tag   `json:"tags"`
	SceneCount   int      `json:"sceneCount"`
	CreatedAt    string   `json:"createdAt"`
	UpdatedAt    string   `json:"updatedAt"`
}

type Plugin struct {
	ID             string                `json:"id"`
	Name           string                `json:"name"`
	PackageName    *string               `json:"packageName,omitempty"`
	LocalBuild     bool                  `json:"localBuild"`
	DisplayName    *string               `json:"displayName,omitempty"`
	IconURL        *string               `json:"iconUrl,omitempty"`
	Description    *string               `json:"description,omitempty"`
	Version        string                `json:"version"`
	Capabilities   []string              `json:"capabilities"`
	Domains        []string              `json:"domains"`
	Enabled        bool                  `json:"enabled"`
	RequiresSolver bool                  `json:"requiresSolver"`
	Available      bool                  `json:"available"`
	InstalledAt    string                `json:"installedAt"`
	UpdatedAt      string                `json:"updatedAt"`
	Settings       []*PluginSettingField `json:"settings"`
	SettingValues  []*PluginSettingValue `json:"settingValues"`
}

type PluginCategory struct {
	ID     string  `json:"id"`
	Name   string  `json:"name"`
	URL    string  `json:"url"`
	Count  int     `json:"count"`
	Poster *string `json:"poster,omitempty"`
}

type PluginPackage struct {
	Name             string  `json:"name"`
	Version          string  `json:"version"`
	Description      *string `json:"description,omitempty"`
	InstalledVersion *string `json:"installedVersion,omitempty"`
}

type PluginSearchResult struct {
	ExternalID      string   `json:"externalId"`
	Title           string   `json:"title"`
	MediaType       string   `json:"mediaType"`
	Plugin          string   `json:"plugin"`
	SourceURL       string   `json:"sourceUrl"`
	Date            *string  `json:"date,omitempty"`
	PosterURL       *string  `json:"posterUrl,omitempty"`
	PreviewImages   []string `json:"previewImages"`
	PreviewVideo    *string  `json:"previewVideo,omitempty"`
	DurationSeconds *int     `json:"durationSeconds,omitempty"`
}

type PluginSettingField struct {
	Key         string  `json:"key"`
	Label       string  `json:"label"`
	Description *string `json:"description,omitempty"`
	Type        string  `json:"type"`
	Required    bool    `json:"required"`
	Default     *string `json:"default,omitempty"`
}

type PluginSettingValue struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type PluginSettingValueInput struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type ProviderSpeed struct {
	URL        string   `json:"url"`
	LoadTimeMs *float64 `json:"loadTimeMs,omitempty"`
	SpeedBps   *float64 `json:"speedBps,omitempty"`
	Error      *string  `json:"error,omitempty"`
}

type Query struct {
}

type RecommendationReason struct {
	Kind       string  `json:"kind"`
	Text       string  `json:"text"`
	EntityID   *string `json:"entityId,omitempty"`
	EntityName *string `json:"entityName,omitempty"`
}

type RecommendationRow struct {
	Key    string                `json:"key"`
	Title  string                `json:"title"`
	Reason *RecommendationReason `json:"reason"`
	Items  []*RecommendedScene   `json:"items"`
}

type RecommendedCategory struct {
	Tag    *Tag     `json:"tag"`
	Scenes []*Scene `json:"scenes"`
}

type RecommendedScene struct {
	Scene  *Scene                `json:"scene"`
	Source string                `json:"source"`
	Reason *RecommendationReason `json:"reason"`
	Score  float64               `json:"score"`
}

type RecordSceneHeatInput struct {
	SceneID         string           `json:"sceneId"`
	DurationSeconds float64          `json:"durationSeconds"`
	Spans           []*HeatSpanInput `json:"spans"`
	Scrubs          []float64        `json:"scrubs"`
}

type SavedFilter struct {
	ID        string       `json:"id"`
	Name      string       `json:"name"`
	Filter    *SceneFilter `json:"filter"`
	CreatedAt string       `json:"createdAt"`
}

type Scene struct {
	ID              string       `json:"id"`
	ExternalID      string       `json:"externalId"`
	SourceURL       string       `json:"sourceUrl"`
	Title           string       `json:"title"`
	Details         *string      `json:"details,omitempty"`
	Date            *string      `json:"date,omitempty"`
	DurationSeconds *int         `json:"durationSeconds,omitempty"`
	Rating          *float64     `json:"rating,omitempty"`
	ViewCount       int          `json:"viewCount"`
	Organized       bool         `json:"organized"`
	PosterPath      *string      `json:"posterPath,omitempty"`
	PreviewVideo    *string      `json:"previewVideo,omitempty"`
	PreviewImages   []string     `json:"previewImages"`
	Studio          *Studio      `json:"studio,omitempty"`
	Performers      []*Performer `json:"performers"`
	Tags            []*Tag       `json:"tags"`
	TagMatch        *string      `json:"tagMatch,omitempty"`
	Related         []*Scene     `json:"related"`
	CreatedAt       string       `json:"createdAt"`
	UpdatedAt       string       `json:"updatedAt"`
}

type SceneFilter struct {
	Search      *string  `json:"search,omitempty"`
	StudioID    *string  `json:"studioId,omitempty"`
	PerformerID *string  `json:"performerId,omitempty"`
	TagID       *string  `json:"tagId,omitempty"`
	MinRating   *float64 `json:"minRating,omitempty"`
	MinDuration *int     `json:"minDuration,omitempty"`
	MaxDuration *int     `json:"maxDuration,omitempty"`
	DateFrom    *string  `json:"dateFrom,omitempty"`
	DateTo      *string  `json:"dateTo,omitempty"`
	Sort        *string  `json:"sort,omitempty"`
	Sources     []string `json:"sources,omitempty"`
}

type SceneFilterInput struct {
	Search      *string  `json:"search,omitempty"`
	StudioID    *string  `json:"studioId,omitempty"`
	PerformerID *string  `json:"performerId,omitempty"`
	TagID       *string  `json:"tagId,omitempty"`
	MinRating   *float64 `json:"minRating,omitempty"`
	MinDuration *int     `json:"minDuration,omitempty"`
	MaxDuration *int     `json:"maxDuration,omitempty"`
	DateFrom    *string  `json:"dateFrom,omitempty"`
	DateTo      *string  `json:"dateTo,omitempty"`
	Sort        *string  `json:"sort,omitempty"`
	Sources     []string `json:"sources,omitempty"`
}

type SceneHeat struct {
	Buckets           []float64 `json:"buckets"`
	BestMomentSeconds *float64  `json:"bestMomentSeconds,omitempty"`
	ThumbnailSeconds  *float64  `json:"thumbnailSeconds,omitempty"`
}

type SceneMarker struct {
	ID         string   `json:"id"`
	Tag        *Tag     `json:"tag,omitempty"`
	Label      *string  `json:"label,omitempty"`
	Seconds    float64  `json:"seconds"`
	EndSeconds *float64 `json:"endSeconds,omitempty"`
	Personal   bool     `json:"personal"`
	CreatedAt  string   `json:"createdAt"`
}

type ScrapePayload struct {
	Success bool    `json:"success"`
	Error   *string `json:"error,omitempty"`
	MediaID *string `json:"mediaId,omitempty"`
}

type SearchSubscription struct {
	ID            string              `json:"id"`
	Kind          SubscriptionKind    `json:"kind"`
	Query         string              `json:"query"`
	Target        *SubscriptionTarget `json:"target,omitempty"`
	Sources       []string            `json:"sources"`
	IntervalHours int                 `json:"intervalHours"`
	Enabled       bool                `json:"enabled"`
	LastRunAt     *string             `json:"lastRunAt,omitempty"`
	NextRunAt     *string             `json:"nextRunAt,omitempty"`
	LastError     *string             `json:"lastError,omitempty"`
	NewCount      int                 `json:"newCount"`
	TotalCount    int                 `json:"totalCount"`
	CreatedAt     string              `json:"createdAt"`
	Scenes        []*Scene            `json:"scenes"`
}

type SearchSuggestion struct {
	Kind SearchSuggestionKind `json:"kind"`
	// Text to show and to search for when chosen.
	Text string `json:"text"`
	// Entity id (tag/performer/studio) when the suggestion is an entity, never the raw record id structure — plain string id like other *Id fields.
	EntityID *string `json:"entityId,omitempty"`
	// Avatar/logo/profile image URL for performers/studios, null otherwise.
	ImageURL *string `json:"imageUrl,omitempty"`
	// Short grey detail line, e.g. '128 videos' or 'Performer'.
	Detail *string `json:"detail,omitempty"`
}

type SettingEntry struct {
	ID          string  `json:"id"`
	Scope       string  `json:"scope"`
	Plugin      *string `json:"plugin,omitempty"`
	Key         string  `json:"key"`
	Value       *string `json:"value,omitempty"`
	Description *string `json:"description,omitempty"`
	UpdatedAt   string  `json:"updatedAt"`
}

type Settings struct {
	MaxConcurrentJobs            int              `json:"maxConcurrentJobs"`
	MaxJobRetries                int              `json:"maxJobRetries"`
	DownloadSpeedLimitKBps       int              `json:"downloadSpeedLimitKBps"`
	AllowDownloadsWhileStreaming bool             `json:"allowDownloadsWhileStreaming"`
	AutoEnrichAfterScrape        bool             `json:"autoEnrichAfterScrape"`
	RequireVpn                   bool             `json:"requireVpn"`
	KindLimits                   []*KindRateLimit `json:"kindLimits"`
}

type Stream struct {
	ID               string   `json:"id"`
	MediaID          string   `json:"mediaId"`
	URL              string   `json:"url"`
	Kind             string   `json:"kind"`
	Label            *string  `json:"label,omitempty"`
	Provider         *string  `json:"provider,omitempty"`
	Resolution       *string  `json:"resolution,omitempty"`
	Width            *int     `json:"width,omitempty"`
	Height           *int     `json:"height,omitempty"`
	Language         *string  `json:"language,omitempty"`
	Format           *string  `json:"format,omitempty"`
	MimeType         *string  `json:"mimeType,omitempty"`
	ExpectedSpeedBps *float64 `json:"expectedSpeedBps,omitempty"`
	FileSizeBytes    *float64 `json:"fileSizeBytes,omitempty"`
	Verified         bool     `json:"verified"`
	PluginName       *string  `json:"pluginName,omitempty"`
	CreatedAt        string   `json:"createdAt"`
	UpdatedAt        string   `json:"updatedAt"`
}

type StreamHeader struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type StreamResult struct {
	URL        string          `json:"url"`
	MimeType   string          `json:"mimeType"`
	Quality    *string         `json:"quality,omitempty"`
	Headers    []*StreamHeader `json:"headers"`
	LoadTimeMs *float64        `json:"loadTimeMs,omitempty"`
	SpeedBps   *float64        `json:"speedBps,omitempty"`
}

type Studio struct {
	ID         string   `json:"id"`
	Name       string   `json:"name"`
	Aliases    []string `json:"aliases"`
	URL        *string  `json:"url,omitempty"`
	Parent     *Studio  `json:"parent,omitempty"`
	ImagePath  *string  `json:"imagePath,omitempty"`
	Details    *string  `json:"details,omitempty"`
	Tags       []*Tag   `json:"tags"`
	SceneCount int      `json:"sceneCount"`
	CreatedAt  string   `json:"createdAt"`
	UpdatedAt  string   `json:"updatedAt"`
}

type Subscription struct {
}

type SubscriptionFeedFilter struct {
	SubscriptionID *string            `json:"subscriptionId,omitempty"`
	Kinds          []SubscriptionKind `json:"kinds,omitempty"`
	NewOnly        *bool              `json:"newOnly,omitempty"`
	UnwatchedOnly  *bool              `json:"unwatchedOnly,omitempty"`
}

type SubscriptionFeedItem struct {
	Scene          *Scene `json:"scene"`
	FoundAt        string `json:"foundAt"`
	SubscriptionID string `json:"subscriptionId"`
	IsNew          bool   `json:"isNew"`
}

type SubscriptionTarget struct {
	ID       string  `json:"id"`
	Name     string  `json:"name"`
	ImageURL *string `json:"imageUrl,omitempty"`
}

type Tag struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Aliases     []string `json:"aliases"`
	Description *string  `json:"description,omitempty"`
	Category    *string  `json:"category,omitempty"`
	SceneCount  int      `json:"sceneCount"`
	CreatedAt   string   `json:"createdAt"`
	UpdatedAt   string   `json:"updatedAt"`
}

type TasteEntry struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	ImagePath *string `json:"imagePath,omitempty"`
	Affinity  float64 `json:"affinity"`
}

type TasteProfile struct {
	SignalCount int           `json:"signalCount"`
	Tags        []*TasteEntry `json:"tags"`
	Performers  []*TasteEntry `json:"performers"`
	Studios     []*TasteEntry `json:"studios"`
	Sites       []*TasteEntry `json:"sites"`
}

type UpdateSettingsInput struct {
	MaxConcurrentJobs            *int                  `json:"maxConcurrentJobs,omitempty"`
	MaxJobRetries                *int                  `json:"maxJobRetries,omitempty"`
	DownloadSpeedLimitKBps       *int                  `json:"downloadSpeedLimitKBps,omitempty"`
	AllowDownloadsWhileStreaming *bool                 `json:"allowDownloadsWhileStreaming,omitempty"`
	AutoEnrichAfterScrape        *bool                 `json:"autoEnrichAfterScrape,omitempty"`
	RequireVpn                   *bool                 `json:"requireVpn,omitempty"`
	KindLimits                   []*KindRateLimitInput `json:"kindLimits,omitempty"`
}

type UpsertSettingEntryInput struct {
	Scope       string  `json:"scope"`
	Plugin      *string `json:"plugin,omitempty"`
	Key         string  `json:"key"`
	Value       string  `json:"value"`
	Description *string `json:"description,omitempty"`
}

type UpsertUserRatingInput struct {
	Media  string  `json:"media"`
	Rating float64 `json:"rating"`
}

type UpsertWatchHistoryInput struct {
	Media           string `json:"media"`
	ProgressSeconds int    `json:"progressSeconds"`
	DurationSeconds *int   `json:"durationSeconds,omitempty"`
	Completed       *bool  `json:"completed,omitempty"`
}

type UserRating struct {
	ID        string  `json:"id"`
	Media     string  `json:"media"`
	Rating    float64 `json:"rating"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}

type VpnStatus struct {
	Connected bool    `json:"connected"`
	Interface *string `json:"interface,omitempty"`
}

type WatchHistory struct {
	ID                 string  `json:"id"`
	Media              string  `json:"media"`
	Scene              *Scene  `json:"scene,omitempty"`
	StartedAt          string  `json:"startedAt"`
	FinishedAt         *string `json:"finishedAt,omitempty"`
	ProgressSeconds    int     `json:"progressSeconds"`
	MaxProgressSeconds int     `json:"maxProgressSeconds"`
	DurationSeconds    *int    `json:"durationSeconds,omitempty"`
	Completed          bool    `json:"completed"`
	UpdatedAt          string  `json:"updatedAt"`
}

type WatchlistItem struct {
	ID        string `json:"id"`
	Media     string `json:"media"`
	CreatedAt string `json:"createdAt"`
}

type ObservationStatus string

const (
	ObservationStatusPending    ObservationStatus = "PENDING"
	ObservationStatusMerged     ObservationStatus = "MERGED"
	ObservationStatusConflicted ObservationStatus = "CONFLICTED"
	ObservationStatusRejected   ObservationStatus = "REJECTED"
)

var AllObservationStatus = []ObservationStatus{
	ObservationStatusPending,
	ObservationStatusMerged,
	ObservationStatusConflicted,
	ObservationStatusRejected,
}

func (e ObservationStatus) IsValid() bool {
	switch e {
	case ObservationStatusPending, ObservationStatusMerged, ObservationStatusConflicted, ObservationStatusRejected:
		return true
	}
	return false
}

func (e ObservationStatus) String() string {
	return string(e)
}

func (e *ObservationStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ObservationStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ObservationStatus", str)
	}
	return nil
}

func (e ObservationStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ObservationStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ObservationStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SearchSuggestionKind string

const (
	SearchSuggestionKindRecent    SearchSuggestionKind = "RECENT"
	SearchSuggestionKindQuery     SearchSuggestionKind = "QUERY"
	SearchSuggestionKindTag       SearchSuggestionKind = "TAG"
	SearchSuggestionKindPerformer SearchSuggestionKind = "PERFORMER"
	SearchSuggestionKindStudio    SearchSuggestionKind = "STUDIO"
)

var AllSearchSuggestionKind = []SearchSuggestionKind{
	SearchSuggestionKindRecent,
	SearchSuggestionKindQuery,
	SearchSuggestionKindTag,
	SearchSuggestionKindPerformer,
	SearchSuggestionKindStudio,
}

func (e SearchSuggestionKind) IsValid() bool {
	switch e {
	case SearchSuggestionKindRecent, SearchSuggestionKindQuery, SearchSuggestionKindTag, SearchSuggestionKindPerformer, SearchSuggestionKindStudio:
		return true
	}
	return false
}

func (e SearchSuggestionKind) String() string {
	return string(e)
}

func (e *SearchSuggestionKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SearchSuggestionKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SearchSuggestionKind", str)
	}
	return nil
}

func (e SearchSuggestionKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SearchSuggestionKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SearchSuggestionKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SubscriptionKind string

const (
	SubscriptionKindSearch    SubscriptionKind = "SEARCH"
	SubscriptionKindStudio    SubscriptionKind = "STUDIO"
	SubscriptionKindPerformer SubscriptionKind = "PERFORMER"
	SubscriptionKindTag       SubscriptionKind = "TAG"
)

var AllSubscriptionKind = []SubscriptionKind{
	SubscriptionKindSearch,
	SubscriptionKindStudio,
	SubscriptionKindPerformer,
	SubscriptionKindTag,
}

func (e SubscriptionKind) IsValid() bool {
	switch e {
	case SubscriptionKindSearch, SubscriptionKindStudio, SubscriptionKindPerformer, SubscriptionKindTag:
		return true
	}
	return false
}

func (e SubscriptionKind) String() string {
	return string(e)
}

func (e *SubscriptionKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SubscriptionKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SubscriptionKind", str)
	}
	return nil
}

func (e SubscriptionKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SubscriptionKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SubscriptionKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
